##########################################################
# Load the tidyverse library
##########################################################
# Install the tidyverse package if you have not already do so. 
# NOTE: You only need to install the package the first time you use it
# NOTE: Lines of code can be run by putting your cursor on the line to be executed and clicking on "Run" above, or hitting "ctrl + enter" ("cmd + return on a Mac). You can also highlight multiple lines of code and run them all together.
install.packages("tidyverse") 

# This line needs to be done every session to load the library
library("tidyverse")

##########################################################
# Load the Cell_counts.xlsx Excel file tab by tab 
##########################################################
# Import the first sheet (Day 0 data) from the Cell_counts.xlsx file located in the Data_in folder and store it as the YPD_D0 data frame.
# The data should all be collected in a single Excel worksheet, with cell counts from each day on different sheets sequentially, starting with the Day 0 data on sheet 1.

# First day of data collection
YPD_D0 <- readxl::read_xlsx ("Data_in/Cell_counts.xlsx", 
                             sheet = 1)

# Second day of data collection
YPD_D1 <- readxl::read_xlsx ("Data_in/Cell_counts.xlsx", 
                             sheet = 2) 

# Repeat the second line of code, changing the "DX" part as appropriate to include additional days of data, depending on your experiment. 
# You should be able to see data tables in the Environment Panel.


##########################################################
# Load the Image_names.xlsx Excel file tab by tab 
##########################################################
# The Image_names.xlsx file should similarly be imported sheet by sheet (increase the number of days, as required)

# First day of data collection
YPD_D0_wellnames <- readxl::read_xlsx ("Data_in/Well_names.xlsx", sheet = 1)

# Second day of data collection
YPD_D1_wellnames <- readxl::read_xlsx ("Data_in/Well_names.xlsx", sheet = 2)

##########################################################
# Removing the unwanted columns from the data tables
##########################################################
# The only essential columns in the YPD_D0 and YPD_D1 data frames are the Filename and two cell counts columns ( Fluor and NonFluor). 
# Select those columns from the data frame. 
# This will overwrite the YPD_D0 and YPD_1 data frames to keep just the selected columns. Do this for the data frame from each day all.

YPD_D0 <- YPD_D0 %>% select(Filename, Fluor, NonFluor)

YPD_D1 <- YPD_D1 %>% select(Filename, Fluor, NonFluor)

###################################
# Renaming the file name column
###################################
# The Filename column of the YPD_D0.xlsx and YPD_D1.xlsx contains the names of the respective images generated in Protocol 2, Step 18. 
# These image names are generated by the EVOS microscope, and it automatically incorporates details of the EVOS protocol, such as plate type, well-identifier and image number, into the name. 
#We need to remove the unnecessary sections of the names, except for the well-identifier (Rep1_Plate_M_p00_0_A01f00d0.PNG).
# Merge the data frames from Cell_counts.xlsx (YPD_D1) and Image_names.xlsx (YPD_D1_imagenames) to create a single file that contains with real image names. 
# We need to extract the well-identifier from the name and replace the original Filename column with the well-identifier. 

YPD_D0 <- YPD_D0 %>%
  mutate(Filename = str_extract(Filename, "[A-G][0-9]+")) %>%
  rename(Well_identifier = Filename)

YPD_D1 <- YPD_D1 %>%
  mutate(Filename = str_extract(Filename, "[A-G][0-9]+")) %>%
  rename(Well_identifier = Filename)

##########################################
# Getting the average cell count per well
##########################################
#Cell counts were acquired from 6 images per well (Protocol 4, Step 40). So, there will be six rows with counts for each well. 
# They will all have the same name in the "Filename" column. We first want to average across them for downstream analysis. 

YPD_D0_avg <- YPD_D0 %>% 
  group_by(Well_identifier) %>%
  summarise(Avg_Fluor_D0 = mean (Fluor, na.rm = T),
            Avg_NonFluor_D0 = mean (NonFluor, na.rm = T))

YPD_D1_avg <- YPD_D1 %>% 
  group_by(Well_identifier) %>%
  summarise(Avg_Fluor_D1 = mean (Fluor, na.rm = T),
            Avg_NonFluor_D1 = mean (NonFluor, na.rm = T))

################################################################################
# Merging YPD_D0_avg and YPD_D1_avg with YPD_D0_wellnames and YPD_D1_wellnames respectively
################################################################################
# 13.	This step will add the details of the actual lines used in Protocol 1 to the data table.

YPD_D0_renamed <- data.frame(YPD_D0_avg, YPD_D0_wellnames) %>% 
  select(Line_name, Avg_NonFluor_D0, Avg_Fluor_D0)

YPD_D1_renamed <- data.frame(YPD_D1_avg, YPD_D1_wellnames) %>% 
  select(Line_name, Avg_NonFluor_D1, Avg_Fluor_D1)


